name: user_app
description: "Library App"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rename: ^2.1.1
  get: ^4.6.5
  google_fonts: ^4.0.4
  pin_code_fields: ^7.4.0
  cached_network_image: ^3.1.0
  carousel_slider: ^5.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  image_picker:
  url_launcher:
  firebase_storage: ^12.3.3
  lottie: ^3.0.0
  otp_autofill: ^4.1.0
  intl:
  flutter_rating_bar:
  flutter_vector_icons:
  flutter_screenutil:
  path_provider:
  flutter_onboarding_slider: ^1.0.11
  shimmer: ^3.0.0
  font_awesome_flutter:
  gif: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

#for app logo
flutter_icons:
  android: true
  ios: true
  image_path: "assets/n_logo.jpg"
  min_sdk_android: 21

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
